//
//  ModalInteractor.swift
//  TFT Asistant
//
//  Created by erdem on 26.10.2019.
//  Copyright (c) 2019 Erdem Isguder. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ModalBusinessLogic
{
    func doSomething(request: Modal.Something.Request)
    func sendDisplayView()
}

protocol ModalDataStore
{
    var detailView: UIView? { get set }
}

class ModalInteractor: ModalBusinessLogic, ModalDataStore
{
    var detailView: UIView?
    
    var presenter: ModalPresentationLogic?
    var worker: ModalWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: Modal.Something.Request)
    {
        worker = ModalWorker()
        worker?.doSomeWork()
        
        let response = Modal.Something.Response()
        presenter?.presentSomething(response: response)
    }
    
    func sendDisplayView() {
        if let detailView = detailView{
            presenter?.presentDetailView(detailView: detailView)
        }
    }
}
