//
//  ItemBuilderWorker.swift
//  TFT Asistant
//
//  Created by erdem on 7.10.2019.
//  Copyright (c) 2019 Erdem Isguder. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Domain

class ItemBuilderWorker
{
    let itemsUseCase: ItemsUseCase
    
    init(itemsUseCase: ItemsUseCase) {
        self.itemsUseCase = itemsUseCase
    }
    
    func getBaseItems(request: ItemBuilder.GetBaseItems.Request) -> ItemBuilder.GetBaseItems.Response{
        let baseItems = itemsUseCase.getItems()?.filter({
            $0.buildsFrom == nil
        })
        
        return ItemBuilder.GetBaseItems.Response(items: baseItems)
    }
}
