//
//  ItemBuilderPresenter.swift
//  TFT Asistant
//
//  Created by erdem on 7.10.2019.
//  Copyright (c) 2019 Erdem Isguder. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ItemBuilderPresentationLogic
{
    func presentBaseItems(response: ItemBuilder.GetBaseItems.Response)
    func presentCombinedItems(response: ItemBuilder.GetCombinedItems.Response)
    func presentSelectedItemDetail(response: ItemBuilder.GetItemByKey.Response)
}

class ItemBuilderPresenter: ItemBuilderPresentationLogic
{
  weak var viewController: ItemBuilderDisplayLogic?
  
  // MARK: Do something
  
    func presentBaseItems(response: ItemBuilder.GetBaseItems.Response) {
        guard let baseItems = response.items else{
            return
        }
        
        let baseItemViewModels = baseItems.map({
            ItemModels.BaseItemViewModel(key: $0.key, name: $0.name, bonus: $0.bonus)
        })
        
        let baseItemsViewModel = ItemModels.BaseItemsViewModel(viewModels: baseItemViewModels)
        
        viewController?.displayBaseItems(baseItems: baseItemsViewModel)
    }
    
    func presentCombinedItems(response: ItemBuilder.GetCombinedItems.Response) {
        if let items = response.items{
            let itemViewModels = items.map({ItemModels.ItemViewModel(name: $0.name, key: $0.key
                , stats: nil, kind: $0.kind, buildsInto: $0.buildsInto, buildsFrom: $0.buildsFrom, champs: $0.champs, bonus: $0.bonus)})
            
            viewController?.displayCombinedItems(combinedItems: ItemModels.ItemsViewModel(itemsViewModel: itemViewModels))
        }
    }
    
    func presentSelectedItemDetail(response: ItemBuilder.GetItemByKey.Response) {
        if let item = response.item{
            let statViewModels = item.stats?.map({ItemStatType(type: $0.name, amount: $0.amount)?.builder()})
            
            let detailViewModel = ItemCombinationDetailViewModel(name: item.name, combinedImageName: item.key, firstImageName: item.buildsFrom?[0], secondImageName: item.buildsFrom?[1], bonus: item.bonus, statViewModels: statViewModels)
            
            viewController?.displaySelectedItemDetail(viewModel: detailViewModel)
        }
    }
}
