//
//  ItemBuilderViewController.swift
//  TFT Asistant
//
//  Created by erdem on 7.10.2019.
//  Copyright (c) 2019 Erdem Isguder. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ItemBuilderDisplayLogic: class
{
    func displayBaseItems(baseItems: ItemModels.BaseItemsViewModel)
    func displayCombinedItems(combinedItems: ItemModels.ItemsViewModel)
    func displaySelectedItemDetail(viewModel: ItemCombinationDetailViewModel)
}

class ItemBuilderViewController: UIViewController, ItemBuilderDisplayLogic
{
    var interactor: ItemBuilderBusinessLogic?
    var router: (NSObjectProtocol & ItemBuilderRoutingLogic & ItemBuilderDataPassing)?
    
    var baseItemsViewModel: ItemModels.BaseItemsViewModel?
    var combinedItemsViewModel: ItemModels.ItemsViewModel?

    //MARK: View bindingds
    
    @IBOutlet weak var baseItemsCollectionView: UICollectionView!
    @IBOutlet weak var baseItemsHeightConstraint: NSLayoutConstraint!
    @IBOutlet weak var baseItemsWidthConstraint: NSLayoutConstraint!
    @IBOutlet weak var combinedItemsCollectionView: UICollectionView!
    @IBOutlet weak var itemDetailView: ItemCombinationDetailView!
    
    @IBOutlet weak var combinedBottomConstraint: NSLayoutConstraint!
    
    // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = ItemBuilderInteractor()
    let presenter = ItemBuilderPresenter()
    let router = ItemBuilderRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
    override func viewDidLoad()
    {
        super.viewDidLoad()
        setupBaseItemsCollectionView()
        setupCombinedCollectionView()
        interactor?.getBaseItems(request: ItemBuilder.GetBaseItems.Request())
    }
    
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        setupBaseItemsCellSize()
        setupCombnidedItemsCellSize()
    }
    
    private func setupBaseItemsCollectionView(){
        self.baseItemsCollectionView.delegate = self
        self.baseItemsCollectionView.dataSource = self
        
        let nib = UINib(nibName: "MultiSelectableCollectionViewCell", bundle: nil)
        baseItemsCollectionView.register(nib, forCellWithReuseIdentifier: String(describing: MultiSelectableCollectionViewCell.self))
    }
    
    private func setupCombinedCollectionView(){
        self.combinedItemsCollectionView.delegate = self
        self.combinedItemsCollectionView.dataSource = self
        
        let nib = UINib(nibName: "SquareCollectionViewCell", bundle: nil)
        combinedItemsCollectionView.register(nib, forCellWithReuseIdentifier: String(describing: SquareCollectionViewCell.self))
    }
    
    private func setupBaseItemsCellSize(){
        let collectionFlowLayout = baseItemsCollectionView.collectionViewLayout as! UICollectionViewFlowLayout
        
        let numberOfItemsInRow: CGFloat = 6
        let lineSpacing: CGFloat = 15
        let itemSpacing: CGFloat = 15
        
        let width = (view.frame.width - (numberOfItemsInRow - 1) * itemSpacing) / numberOfItemsInRow
        
        collectionFlowLayout.itemSize = CGSize(width: width, height: width)
        collectionFlowLayout.minimumLineSpacing = lineSpacing
        collectionFlowLayout.minimumInteritemSpacing = itemSpacing
        
        let wantedColumnItemCount: CGFloat = 5
        let wantedRowItemCount: CGFloat = 2
        
        baseItemsWidthConstraint.constant = (width * wantedColumnItemCount) + (itemSpacing * (wantedColumnItemCount - 1))
        baseItemsHeightConstraint.constant = (width * wantedRowItemCount) + (lineSpacing * (wantedRowItemCount - 1))
    }
    
    private func setupCombnidedItemsCellSize(){
        let collectionFlowLayout = combinedItemsCollectionView.collectionViewLayout as! UICollectionViewFlowLayout
        
        let numberOfItemsInRow: CGFloat = 6
        let lineSpacing: CGFloat = 15
        let itemSpacing: CGFloat = 15
        
        let width = (combinedItemsCollectionView.frame.width - (numberOfItemsInRow - 1) * itemSpacing) / numberOfItemsInRow
        
        collectionFlowLayout.itemSize = CGSize(width: width, height: width)
        collectionFlowLayout.minimumLineSpacing = lineSpacing
        collectionFlowLayout.minimumInteritemSpacing = itemSpacing
    }
  
  // MARK: Actions
    @IBAction func didClearSectionClick(_ sender: Any) {
        
    }
    
    //@IBOutlet weak var nameTextField: UITextField!
    func displayBaseItems(baseItems: ItemModels.BaseItemsViewModel) {
        baseItemsViewModel = baseItems
        baseItemsCollectionView.reloadData()
    }
    
    func displayCombinedItems(combinedItems: ItemModels.ItemsViewModel) {
        combinedItemsViewModel = combinedItems
        combinedItemsCollectionView.reloadData()        
    }
    
    func displaySelectedItemDetail(viewModel: ItemCombinationDetailViewModel) {
        itemDetailView.viewModel = viewModel
        combinedBottomConstraint.constant = itemDetailView.frame.height
    }
}

// TODO: Find a better way than if else
extension ItemBuilderViewController: UICollectionViewDataSource, UICollectionViewDelegate{
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        if collectionView == baseItemsCollectionView{
            return baseItemsViewModel?.viewModels?.count ?? 0
        }
        
        if collectionView == combinedItemsCollectionView{
            return combinedItemsViewModel?.itemsViewModel?.count ?? 0
        }
        
        return 0
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        
        if collectionView == baseItemsCollectionView{
            let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "MultiSelectableCollectionViewCell", for: indexPath) as! MultiSelectableCollectionViewCell
            
            if let item = baseItemsViewModel?.viewModels?[indexPath.row], let key = item.key{
                let cellViewModel = MultiSelectableCollectionViewModel(imageName: key)
                cell.viewModel = cellViewModel
            }
            
            return cell
        }
        
        if collectionView == combinedItemsCollectionView{
            let cell = collectionView.dequeueReusableCell(withReuseIdentifier: String(describing: SquareCollectionViewCell.self), for: indexPath) as! SquareCollectionViewCell
            
            if let item = combinedItemsViewModel?.itemsViewModel?[indexPath.row], let key = item.key{
                cell.imageView.image = UIImage(named: key)
            }
            
            return cell
        }
        
        return UICollectionViewCell()
    }
    
    func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        if collectionView == baseItemsCollectionView {
            let cell = collectionView.cellForItem(at: indexPath) as! MultiSelectableCollectionViewCell
            let isSelected = cell.didSelect()
            if let clickedItem = baseItemsViewModel?.viewModels?[indexPath.row],
                let itemkey = clickedItem.key{
                interactor?.chooseItem(isSelected: isSelected, key: itemkey)
            }
        }
        
        if collectionView == combinedItemsCollectionView{
            if let itemKey = combinedItemsViewModel?.itemsViewModel?[indexPath.row].key{
                interactor?.getSelectedItemDetail(request: Combinations.GetItemByKey.Request(key: itemKey))
            }
        }
    }
}
