//
//  ItemBuilderInteractor.swift
//  TFT Asistant
//
//  Created by erdem on 7.10.2019.
//  Copyright (c) 2019 Erdem Isguder. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import LocalPlatform
import Domain

protocol ItemBuilderBusinessLogic
{
    func getBaseItems(request: ItemBuilder.GetBaseItems.Request)
}

protocol ItemBuilderDataStore
{
    var baseItems: [Item]? {get set}
}

class ItemBuilderInteractor: ItemBuilderBusinessLogic, ItemBuilderDataStore
{
  var presenter: ItemBuilderPresentationLogic?
  let worker: ItemBuilderWorker = ItemBuilderWorker(itemsUseCase: LocalPlatform.UseCaseProvider().makeItemsUseCase())

    var baseItems: [Item]?
  // MARK: Do something
  
    func getBaseItems(request: ItemBuilder.GetBaseItems.Request) {
        let response = worker.getBaseItems(request: request)
        
        if response.items != nil{
            presenter?.presentBaseItems(response: response)
        }
    }
}
