//
//  CombinationsPresenter.swift
//  TFT Asistant
//
//  Created by erdem on 3.10.2019.
//  Copyright (c) 2019 Erdem Isguder. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CombinationsPresentationLogic
{
    func presentAllItems(response: Combinations.GetItems.Response)
    func presentItem(response: Combinations.GetItemByKey.Response)
    func presentItem(response: Combinations.GetItemByName.Response)
}

class CombinationsPresenter: CombinationsPresentationLogic
{
    weak var viewController: CombinationsDisplayLogic?
  
    func presentAllItems(response: Combinations.GetItems.Response) {
        if let items = response.items{
            let itemViewModels = items.map({Combinations.ItemViewModel(name: $0.name, key: $0.key
                , stats: $0.stats, kind: $0.kind, buildsInto: $0.buildsInto, buildsFrom: $0.buildsFrom, champs: $0.champs)})
            
            viewController?.displayItems(viewModel: Combinations.ItemsViewModel(itemsViewModel: itemViewModels))
        }
    }
    
    func presentItem(response: Combinations.GetItemByKey.Response) {
        if let item = response.item{
            
        }
    }
    
    func presentItem(response: Combinations.GetItemByName.Response) {
        if let item = response.item{
            
        }
    }
    
}
