//
//  ChampionDetailPresenter.swift
//  TFT Asistant
//
//  Created by erdem on 28.10.2019.
//  Copyright (c) 2019 Erdem Isguder. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChampionDetailPresentationLogic
{
    func presentChampionDetail(championViewModel: Champions.ChampionViewModel)
}

class ChampionDetailPresenter: ChampionDetailPresentationLogic
{
  weak var viewController: ChampionDetailDisplayLogic?
  
    func presentChampionDetail(championViewModel: Champions.ChampionViewModel) {
        viewController?.displayChampionDetail(championViewModel: championViewModel)
    }
}
