//
//  ChampionDetailInteractor.swift
//  TFT Asistant
//
//  Created by erdem on 28.10.2019.
//  Copyright (c) 2019 Erdem Isguder. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChampionDetailBusinessLogic
{
    func getChampionDetail()
}

protocol ChampionDetailDataStore
{
    var championViewModel: Champions.ChampionViewModel? { get set }
}

class ChampionDetailInteractor: ChampionDetailBusinessLogic, ChampionDetailDataStore
{
    var presenter: ChampionDetailPresentationLogic?
    var worker: ChampionDetailWorker?
    
    var championViewModel: Champions.ChampionViewModel?
    
    func getChampionDetail() {
        if let viewModel = championViewModel{
            presenter?.presentChampionDetail(championViewModel: viewModel)
        }
    }
}
