//
//  TraitsInteractor.swift
//  TFT Asistant
//
//  Created by erdem on 28.10.2019.
//  Copyright (c) 2019 Erdem Isguder. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import LocalPlatform

protocol TraitsBusinessLogic
{
    func getTraits(request: Traits.GetAllTraits.Request)
}

protocol TraitsDataStore
{
    
}

class TraitsInteractor: TraitsBusinessLogic, TraitsDataStore
{
    var presenter: TraitsPresentationLogic?
    var worker: TraitsWorker = TraitsWorker(championUseCase: LocalPlatform.UseCaseProvider().makeChampionsUseCase(),
                                            originsUseCase: LocalPlatform.UseCaseProvider().makeOriginsUseCase(),
                                            classesUseCase: LocalPlatform.UseCaseProvider().makeClassesUseCase())
    
    func getTraits(request: Traits.GetAllTraits.Request) {
        let response = worker.getAllTraits()
        presenter?.presentTraits(response: response)
    }
    
}
