//
//  BaseItemsPresenter.swift
//  TFT Asistant
//
//  Created by erdem on 6.10.2019.
//  Copyright (c) 2019 Erdem Isguder. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BaseItemsPresentationLogic
{
    func presentBaseItems(response: BaseItems.GetBaseItems.Response)
}

class BaseItemsPresenter: BaseItemsPresentationLogic
{
  weak var viewController: BaseItemsDisplayLogic?
  
  // MARK: Do something
    
    func presentBaseItems(response: BaseItems.GetBaseItems.Response) {
        guard let baseItems = response.items else{
            return
        }
        
        let baseItemViewModels = baseItems.map({
            BaseItems.GetBaseItems.BaseItemViewModel(key: $0.key, name: $0.name, bonus: $0.bonus)
        })
        
        let baseItemsViewModel = BaseItems.GetBaseItems.BaseItemsViewModel(viewModels: baseItemViewModels)
        
        viewController?.displayBaseItems(baseItems: baseItemsViewModel)
    }
}
