//
//  BaseItemsPresenter.swift
//  TFT Asistant
//
//  Created by erdem on 6.10.2019.
//  Copyright (c) 2019 Erdem Isguder. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BaseItemsPresentationLogic
{
    func presentBaseItems(response: BaseItems.GetBaseItems.Response)
    func presentCombinedItems(response: BaseItems.GetCombinedItems.Response)
}

class BaseItemsPresenter: BaseItemsPresentationLogic
{
  weak var viewController: BaseItemsDisplayLogic?
  
  // MARK: Do something
    
    func presentBaseItems(response: BaseItems.GetBaseItems.Response) {
        guard let baseItems = response.items else{
            return
        }
        
        let baseItemViewModels = baseItems.map({
            ItemModels.BaseItemViewModel(key: $0.key, name: $0.name, bonus: $0.bonus)
        })
        
        let baseItemsViewModel = ItemModels.BaseItemsViewModel(viewModels: baseItemViewModels)
        
        viewController?.displayBaseItems(baseItems: baseItemsViewModel)
    }
    
    
    func presentCombinedItems(response: BaseItems.GetCombinedItems.Response) {
        if let combinedItems = response.items?.map({ item -> ItemCombinationDetailViewModel in
            let statViewModels = item.stats?.map({ ItemStatType(type: $0.name, amount: $0.amount)?.builder()})
            return ItemCombinationDetailViewModel(name: item.name,
                                           combinedImageName: item.key,
                                           firstImageName: item.buildsFrom?[0],
                                           secondImageName: item.buildsFrom?[1],
                                           bonus: item.bonus,
                                           statViewModels: statViewModels,
                                           showSeparator: false)}){
            viewController?.displayBuildableItems(buildableItems: combinedItems)
            
        }
    }
    
}
