//
//  ChampionsPresenter.swift
//  TFT Asistant
//
//  Created by Erdem Isguder on 22.10.2019.
//  Copyright (c) 2019 Erdem Isguder. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChampionsPresentationLogic
{
    func presentChampions(response: Champions.GetChampionsOrderedByTier.Response)
    func presentChampionDetail()
}

class ChampionsPresenter: ChampionsPresentationLogic
{
  weak var viewController: ChampionsDisplayLogic?
  
    func presentChampions(response: Champions.GetChampionsOrderedByTier.Response) {
        guard let champions = response.champions else{
            viewController?.displayChampions(viewModel: nil)
            return
        }
        
        let championsViewModel = champions.map{
            Champions.ChampionViewModel(name: $0.key, origin: $0.origin, championClass: $0.championClass, cost: $0.cost, ability: $0.ability, items: $0.items, stats: $0.stats)
        }
        
        viewController?.displayChampions(viewModel: Champions.GetChampionsOrderedByTier.ViewModel(championViewModels: championsViewModel))
    }
    
    func presentChampionDetail() {
        viewController?.displayChampionDetail()
    }
}
