//
//  ChampionsRouter.swift
//  TFT Asistant
//
//  Created by Erdem Isguder on 22.10.2019.
//  Copyright (c) 2019 Erdem Isguder. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ChampionsRoutingLogic
{
    func routeToChampionDetail()
}

protocol ChampionsDataPassing
{
    var dataStore: ChampionsDataStore? { get }
}

class ChampionsRouter: NSObject, ChampionsRoutingLogic, ChampionsDataPassing
{
    weak var viewController: ChampionsViewController?
    var dataStore: ChampionsDataStore?
    
    // MARK: Routing
    
    func routeToChampionDetail()
    {
        let storyboard = UIStoryboard(name: "ChampionDetail", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "ChampionDetailViewController") as! ChampionDetailViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToModal(source: dataStore!, destination: &destinationDS)
        navigateToModal(source: viewController!, destination: destinationVC)
    }
    
    // MARK: Navigation
    
    func navigateToModal(source: ChampionsViewController, destination: ChampionDetailViewController)
    {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToModal(source: ChampionsDataStore, destination: inout ChampionDetailDataStore)
    {
        destination.championViewModel = source.championViewModel
    }
}
