//
//  ChampionsPresenter.swift
//  TFT Asistant
//
//  Created by Erdem Isguder on 22.10.2019.
//  Copyright (c) 2019 Erdem Isguder. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChampionsPresentationLogic
{
  func presentSomething(response: Champions.Something.Response)
}

class ChampionsPresenter: ChampionsPresentationLogic
{
  weak var viewController: ChampionsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Champions.Something.Response)
  {
    let viewModel = Champions.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
