//
//  ChampionsWorker.swift
//  TFT Asistant
//
//  Created by Erdem Isguder on 22.10.2019.
//  Copyright (c) 2019 Erdem Isguder. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ChampionsWorker
{
    let useCase: ChampionsUseCase
    
    init(useCase: ChampionsUseCase) {
        self.useCase = useCase
    }
    
    func getChampionsOrderedByTier() -> [Champion]?{
        let champions = useCase.getChampions()?.sorted { (champ1, champ2) -> Bool in
            if champ1.cost < champ2.cost{
                return true
            }
            
            return champ1.name.compare(champ2.name) == ComparisonResult.orderedAscending
        }
        
        return champions
    }
}
