//
//  ChampionsInteractor.swift
//  TFT Asistant
//
//  Created by Erdem Isguder on 22.10.2019.
//  Copyright (c) 2019 Erdem Isguder. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import LocalPlatform

protocol ChampionsBusinessLogic
{
    func getChampionsOrderedByTier(request: Champions.GetChampionsOrderedByTier.Request) ->
        Champions.GetChampionsOrderedByTier.Response
}

protocol ChampionsDataStore
{
  //var name: String { get set }
}

class ChampionsInteractor: ChampionsBusinessLogic, ChampionsDataStore
{

    var presenter: ChampionsPresentationLogic?
    var worker: ChampionsWorker = ChampionsWorker(useCase: LocalPlatform.UseCaseProvider().makeChampionsUseCase())
  
    func getChampionsOrderedByTier(request: Champions.GetChampionsOrderedByTier.Request) -> Champions.GetChampionsOrderedByTier.Response {
        
        let response = Champions.GetChampionsOrderedByTier.Response(champions: worker.getChampionsOrderedByTier())
        return response
    }
}
